server:
  tomcat:
    accesslog:
      enabled: true

logging:
  level:
    root: info

spring:
  application:
    name: order

  mvc:
    problemdetails:
      enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:order;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true

  jackson:
    serialization:
      write-null-map-values: false
jwt:
  secret: a2FrYW9iYW5rX29yZGVyX3NlY3JldGtleV8yMDI0MDUzMQ==

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:tcp://localhost/~/order;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 10000

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: info
    org:
      springframework: info
      hibernate:
        SQL: debug
