server:
  tomcat:
    accesslog:
      enabled: true

logging:
  level:
    root: warn

spring:
  application:
    name: order

  mvc:
    problemdetails:
      enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:order
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  jackson:
    serialization:
      write-null-map-values: false

jwt:
  secret: a2FrYW9iYW5rX29yZGVyX3NlY3JldGtleV8yMDI0MDUzMQ==

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:tcp://localhost/~/order;MODE=MySQL

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
    org:
      springframework: info
      hibernate:
        SQL: debug
